# Generated by Django 3.1.3 on 2020-11-05 18:20

from django.db import migrations, models
import tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='processed_videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='court_tracking_file',
            field=models.FileField(max_length=1000, null=True, upload_to=tracking.models.generate_dirpath, verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='ocr_file',
            field=models.FileField(max_length=1000, null=True, upload_to=tracking.models.generate_dirpath, verbose_name=''),
        ),
        migrations.AddField(
            model_name='video',
            name='team_classification_file',
            field=models.FileField(max_length=1000, null=True, upload_to=tracking.models.generate_dirpath, verbose_name=''),
        ),
    ]
