# Generated by Django 3.1.3 on 2020-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20201105_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='court_tracking_file',
            field=models.FileField(max_length=1000, null=True, upload_to='tracking/tracking_results', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='ocr_file',
            field=models.FileField(max_length=1000, null=True, upload_to='tracking/tracking_results', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='team_classification_file',
            field=models.FileField(max_length=1000, null=True, upload_to='tracking/tracking_results', verbose_name=''),
        ),
    ]
