# Generated by Django 3.1.3 on 2020-11-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20201105_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='team_classification_file',
            new_name='player_tracking_file',
        ),
    ]
